pre-commit:
  parallel: true
  commands:
    eslint:
      glob: '*.{ts,tsx,js,jsx,mjs,cjs}'
      run: pnpm exec eslint --fix {staged_files}
      stage_fixed: true
    prettier:
      glob: '*.{ts,tsx,js,jsx,mjs,cjs,json,md,yml,yaml}'
      run: pnpm exec prettier --write {staged_files}
      stage_fixed: true
    typecheck:
      run: pnpm exec tsc --noEmit

commit-msg:
  commands:
    commitlint:
      run: pnpm exec commitlint --edit {1}
